# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/AboutSheet.qml) \
        $$quote($$BASEDIR/assets/AddCatSheet.qml) \
        $$quote($$BASEDIR/assets/AddItemSheet.qml) \
        $$quote($$BASEDIR/assets/AddListSheet.qml) \
        $$quote($$BASEDIR/assets/AllListsTab.qml) \
        $$quote($$BASEDIR/assets/AppLogic.qml) \
        $$quote($$BASEDIR/assets/AppStorage.qml) \
        $$quote($$BASEDIR/assets/CatTabDef.qml) \
        $$quote($$BASEDIR/assets/ItemPageDef.qml) \
        $$quote($$BASEDIR/assets/ModelManager.qml) \
        $$quote($$BASEDIR/assets/SettingsSheet.qml) \
        $$quote($$BASEDIR/assets/SharePickerSheet.qml) \
        $$quote($$BASEDIR/assets/cover.qml) \
        $$quote($$BASEDIR/assets/desktop.ini) \
        $$quote($$BASEDIR/assets/images/about.png) \
        $$quote($$BASEDIR/assets/images/berrylife.png) \
        $$quote($$BASEDIR/assets/images/category.png) \
        $$quote($$BASEDIR/assets/images/copy.png) \
        $$quote($$BASEDIR/assets/images/delete.png) \
        $$quote($$BASEDIR/assets/images/desktop.ini) \
        $$quote($$BASEDIR/assets/images/email.png) \
        $$quote($$BASEDIR/assets/images/home.png) \
        $$quote($$BASEDIR/assets/images/listedit.png) \
        $$quote($$BASEDIR/assets/images/newcategory.png) \
        $$quote($$BASEDIR/assets/images/plus.png) \
        $$quote($$BASEDIR/assets/images/selectmore.png) \
        $$quote($$BASEDIR/assets/images/settings.png) \
        $$quote($$BASEDIR/assets/images/share.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/main_qml_patch.js)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/OrientationSensor.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/OrientationSensor.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp) \
        $$quote($$BASEDIR/src/fileio.h)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
